import { StyleSheet, Dimensions, Platform } from 'react-native';
const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  // ========== CONTENEUR PRINCIPAL ==========
  container: {
    flex: 1,
    backgroundColor: '#FAFBFC',
    paddingBottom: 85,
  },

  // ========== HEADER ÉPURÉ ==========
  header: {
    paddingTop: 40,
    paddingHorizontal: 18,
    paddingBottom: 12,
    backgroundColor: '#2E7D32',
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  headerSearchBarContainer: {
    paddingHorizontal: 0,
    marginTop: 8,
    marginBottom: 0,
  },
  headerSearchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingHorizontal: 12,
    height: 38,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  headerSearchPlaceholder: {
    marginLeft: 8,
    color: '#BDBDBD',
    fontSize: 12,
    fontWeight: '500',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
  },
  welcomeText: {
    color: '#C8E6C9',
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  userName: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '800',
    marginTop: 1,
  },
  headerRight: {
    position: 'relative',
    marginLeft: 10,
  },
  notificationButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255,255,255,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  notificationBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#FF5252',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#2E7D32',
  },
  notificationBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '800',
  },
  creditInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    marginTop: 8,
  },
  creditText: {
    color: '#fff',
    fontSize: 13,
    marginLeft: 8,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  image: {
    width: 48,
    height: 48,
    borderRadius: 24,
  },

  // ========== CONTENU ==========
  content: {
    flex: 1,
    paddingHorizontal: 0,
  },

  // ========== Barre de recherche ==========
  searchBarContainer: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    backgroundColor: '#FAFBFC',
    borderBottomWidth: 0,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E8E8E8',
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 44,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#2D3748',
  },
  searchLoader: {
    marginLeft: 8,
  },

  // ========== STATS RAPIDES MINIMALES ==========
  quickStatsContainer: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 20,
    marginTop: 12,
    paddingHorizontal: 18,
  },
  quickStatCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 12,
    borderLeftWidth: 4,
    elevation: 1,
    shadowColor: '#2E7D32',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickStatCardContent: {
    flexDirection: 'column',
    alignItems: 'center',
    marginBottom: 8,
  },
  quickStatCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 0,
    flex: 1,
  },
  quickStatIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 0,
    marginBottom: 6,
  },
  quickStatValue: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1a1a1a',
    letterSpacing: -0.4,
  },
  quickStatTitle: {
    fontSize: 10,
    color: '#757575',
    fontWeight: '700',
    marginBottom: 0,
    letterSpacing: 0.1,
  },
  quickStatSubtitle: {
    fontSize: 9,
    color: '#BDBDBD',
    fontWeight: '500',
    display: 'none',
  },
  quickStatContent: {
    flex: 1,
    marginLeft: 0,
  },

  // ========== SECTIONS ==========
  section: {
    paddingHorizontal: 16,
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#1a1a1a',
    letterSpacing: 0.3,
  },
  sectionSubtitle: {
    fontSize: 12,
    color: '#999',
    fontWeight: '500',
    marginTop: 4,
    letterSpacing: 0.1,
  },
  seeMoreButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E8F5E9',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    gap: 4,
  },
  seeMoreText: {
    fontSize: 13,
    color: '#2E7D32',
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  sectionAction: {
    fontSize: 13,
    color: '#2E7D32',
    fontWeight: '700',
    letterSpacing: 0.2,
  },

  // ========== LIVRAISON EN COURS - COMPACT ==========
  commandeCard: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
    borderLeftWidth: 5,
    borderLeftColor: '#FF9800',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
  },
  commandeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  commandeId: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1a1a1a',
    letterSpacing: 0.1,
  },
  statutBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    gap: 4,
  },
  statutText: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.1,
  },
  commandeProduit: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1a1a1a',
    marginBottom: 8,
    letterSpacing: 0.1,
  },
  commandeType: {
    fontSize: 12,
    color: '#757575',
    marginBottom: 0,
    fontWeight: '500',
    display: 'none',
  },
  commandeQuantite: {
    fontSize: 12,
    color: '#999',
    marginBottom: 8,
    fontWeight: '500',
  },
  commandeDetails: {
    borderTopWidth: 0,
    borderTopColor: '#F5F5F5',
    paddingTop: 0,
    gap: 4,
    display: 'none',
  },
  commandeDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  commandeDetailText: {
    fontSize: 12,
    color: '#666',
    fontWeight: '500',
    flex: 1,
  },
  trackButton: {
    marginTop: 10,
    borderRadius: 10,
    overflow: 'hidden',
  },
  trackButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    gap: 6,
  },
  trackButtonText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.2,
  },

  // ========== GRILLE PRODUITS - ESSENTIEL ==========
  productsGrid: {
    flexDirection: 'row',
    gap: 18,
    paddingHorizontal: 18,
    paddingVertical: 8,
  },
  productsGridContent: {
    flexDirection: 'row',
    gap: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  productCard: {
    width: 175,
    backgroundColor: '#fff',
    borderRadius: 18,
    overflow: 'hidden',
    elevation: 3,
    shadowColor: '#2E7D32',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
  },
  productImageContainer: {
    position: 'relative',
    backgroundColor: '#F8FAFC',
    height: 140,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#E8F5E9',
  },
  productImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  outOfStockOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  outOfStockText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  productName: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1a1a1a',
    paddingHorizontal: 12,
    paddingTop: 14,
    letterSpacing: 0.2,
  },
  productType: {
    fontSize: 11,
    color: '#2E7D32',
    paddingHorizontal: 12,
    marginTop: 4,
    fontWeight: '700',
    textTransform: 'capitalize',
  },
  productPrice: {
    fontSize: 15,
    fontWeight: '900',
    color: '#2E7D32',
    paddingHorizontal: 12,
    marginTop: 8,
    letterSpacing: -0.3,
  },
  productDistributor: {
    fontSize: 10,
    color: '#999',
    paddingHorizontal: 10,
    marginTop: 2,
    fontWeight: '500',
    display: 'none',
  },
  productStock: {
    fontSize: 11,
    fontWeight: '700',
    paddingHorizontal: 12,
    marginTop: 6,
    letterSpacing: 0.1,
    paddingBottom: 10,
  },
  productStockIn: {
    color: '#2E7D32',
  },
  productStockOut: {
    color: '#E53935',
  },
  productDistance: {
    fontSize: 10,
    color: '#2E7D32',
    paddingHorizontal: 10,
    paddingBottom: 10,
    fontWeight: '700',
    backgroundColor: '#E8F5E9',
    paddingVertical: 6,
    borderRadius: 6,
    marginTop: 6,
  },
  locationButton: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#2E7D32',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#2E7D32',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },

  // ========== CONTENEUR ACTIONS RAPIDES PROFESSIONNEL ==========
  quickActions: {
    paddingHorizontal: 18,
    marginBottom: 28,
    paddingVertical: 0,
  },
  actionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 0,
    justifyContent: 'space-between',
  },
  quickActionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 12,
    justifyContent: 'space-between',
  },
  quickActionButton: {
    width: '48%',
    backgroundColor: '#fff',
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
    shadowColor: '#2E7D32',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 5,
    borderWidth: 1,
    borderColor: '#E8E8E8',
  },
  quickActionText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#2E7D32',
    marginTop: 10,
    textAlign: 'center',
    letterSpacing: 0.2,
  },

  // ========== INFO DISTANCE AMÉLIORÉ ==========
  distanceInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    padding: 10,
    backgroundColor: '#E8F5E9',
    borderRadius: 10,
    borderLeftWidth: 0,
  },
  distanceInfoText: {
    marginLeft: 8,
    fontSize: 12,
    color: '#2E7D32',
    flex: 1,
    fontWeight: '700',
  },

  // ========== États de chargement et d'erreur ==========
  loadingContainer: {
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: '#718096',
    textAlign: 'center',
  },
  errorContainer: {
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FEF2F2',
    borderRadius: 12,
    marginVertical: 10,
  },
  errorText: {
    marginTop: 12,
    fontSize: 14,
    color: '#E53E3E',
    textAlign: 'center',
    marginBottom: 16,
  },
  retryButton: {
    backgroundColor: '#2E7D32',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
  },
  retryButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },

  // ========== États vides ==========
  noResultsContainer: {
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F7FAFC',
    borderRadius: 12,
    marginVertical: 10,
  },
  noResults: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4A5568',
    marginTop: 12,
    textAlign: 'center',
  },
  noResultsSubtext: {
    fontSize: 14,
    color: '#718096',
    marginTop: 8,
    textAlign: 'center',
  },

  // ========== HISTORIQUE RÉCENT - COMPACT ==========
  historyCard: {
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#E8E8E8',
    elevation: 3,
    shadowColor: '#2E7D32',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 5,
  },
  historyCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  historyCardLeft: {
    flex: 1,
  },
  historyCardMiddle: {
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  historyCardBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  historyDate: {
    fontSize: 11,
    color: '#999',
    fontWeight: '500',
    marginTop: 4,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
  },
  statusText: {
    fontSize: 10,
    fontWeight: '700',
    marginLeft: 4,
    textTransform: 'uppercase',
  },
  historyProduct: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1a1a1a',
  },
  historyDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    gap: 12,
  },
  historyQuantity: {
    fontSize: 12,
    color: '#757575',
    fontWeight: '600',
  },
  historyTotal: {
    fontSize: 14,
    fontWeight: '800',
    color: '#2E7D32',
  },
  historyDistributor: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  historyDistributorText: {
    fontSize: 11,
    color: '#666',
    fontWeight: '500',
  },

  // ========== FOOTER MODERNE ÉPURÉ ==========
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    height: 95,
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    elevation: 12,
    shadowColor: '#2E7D32',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    paddingBottom: 20,
  },
  footerTab: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    minWidth: 70,
    borderRadius: 14,
    transition: 'all 0.3s ease',
  },
  activeTab: {
    backgroundColor: '#E8F5E9',
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 10,
    elevation: 2,
    shadowColor: '#2E7D32',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
  },
  footerTabText: {
    fontSize: 12,
    color: '#9E9E9E',
    marginTop: 6,
    fontWeight: '600',
    textAlign: 'center',
    letterSpacing: 0.4,
  },
  activeTabText: {
    color: '#2E7D32',
    fontWeight: '700',
    fontSize: 12,
  },

  // ========== Modal ==========
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#fff',
    width: '90%',
    borderRadius: 16,
    padding: 20,
    elevation: 5,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2D3748',
    flex: 1,
  },
  modalProductImage: {
    width: 80,
    height: 80,
    resizeMode: 'contain',
    alignSelf: 'center',
    marginBottom: 16,
  },
  modalProductName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2D3748',
    textAlign: 'center',
    marginBottom: 8,
  },
  modalProductPrice: {
    fontSize: 18,
    color: '#2E7D32',
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 12,
  },
  modalProductDesc: {
    fontSize: 14,
    color: '#718096',
    textAlign: 'center',
    marginBottom: 8,
  },
  modalProductDistributor: {
    fontSize: 14,
    color: '#718096',
    textAlign: 'center',
    marginBottom: 16,
  },
  quantityContainer: {
    marginBottom: 24,
  },
  quantityLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2D3748',
    marginBottom: 12,
  },
  quantityControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#E8F5E8',
    justifyContent: 'center',
    alignItems: 'center',
  },
  quantityInput: {
    width: 60,
    height: 40,
    backgroundColor: '#F7FAFC',
    borderRadius: 8,
    textAlign: 'center',
    marginHorizontal: 16,
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2D3748',
  },
  totalContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#F7FAFC',
    borderRadius: 12,
    marginBottom: 24,
  },
  totalLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2D3748',
  },
  totalAmount: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2E7D32',
  },
  orderButton: {
    borderRadius: 12,
    overflow: 'hidden',
  },
  orderButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 24,
  },
  orderButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  insufficientCredit: {
    color: '#E53935',
    fontSize: 14,
    marginTop: 8,
    textAlign: 'center',
  },

  // ========== Recherche ==========
  searchContent: {
    flex: 1,
    padding: 16,
  },
  searchResultsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    flex: 1,
  },
  resultsCount: {
    fontSize: 14,
    color: '#718096',
    fontWeight: '500',
  },
  searchResultsGrid: {
    paddingBottom: 20,
  },
  columnWrapper: {
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  searchFilters: {
    marginBottom: 20,
  },
  filterTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2D3748',
    marginBottom: 12,
  },
  filterScroll: {
    flexGrow: 0,
  },
  filterChip: {
    backgroundColor: '#F7FAFC',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  filterChipText: {
    fontSize: 14,
    color: '#4A5568',
    fontWeight: '500',
  },
  clearSearchButton: {
    backgroundColor: '#2E7D32',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    marginTop: 16,
  },
  clearSearchButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },

  // ========== Modals spécifiques ==========
  modalTitleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flex: 1,
  },
  markAllReadButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#2E7D32',
    borderRadius: 6,
  },
  markAllReadText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '500',
  },
  closeButton: {
    padding: 4,
  },
  notificationItem: {
    flexDirection: 'row',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    backgroundColor: '#fff',
  },
  unreadNotification: {
    backgroundColor: '#F0F9FF',
    borderLeftWidth: 3,
    borderLeftColor: '#2E7D32',
  },
  notificationIconContainer: {
    marginRight: 12,
    justifyContent: 'center',
  },
  notificationContent: {
    flex: 1,
    position: 'relative',
  },
  notificationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  notificationTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2D3748',
    flex: 1,
    marginRight: 8,
  },
  notificationDate: {
    fontSize: 12,
    color: '#718096',
  },
  notificationMessage: {
    fontSize: 13,
    color: '#4A5568',
    lineHeight: 18,
  },
  unreadDot: {
    position: 'absolute',
    top: 2,
    right: 2,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#2E7D32',
  },
  notificationAction: {
    padding: 4,
    marginLeft: 8,
    justifyContent: 'center',
  },
  noNotifications: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
  },
  noNotificationsText: {
    fontSize: 16,
    color: '#718096',
    marginTop: 12,
    textAlign: 'center',
  },
  noNotificationsSubtext: {
    fontSize: 14,
    color: '#A0AEC0',
    marginTop: 8,
    textAlign: 'center',
  },
  searchModalContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  searchModalHeader: {
    backgroundColor: '#fff',
    paddingTop: 16,
    paddingHorizontal: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  searchModalSearchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F7FAFC',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  searchModalInput: {
    flex: 1,
    fontSize: 16,
    color: '#2D3748',
    marginLeft: 8,
    paddingVertical: 4,
  },
  searchModalCloseButton: {
    padding: 4,
    marginLeft: 8,
  },
});

export default styles;
